# Node.js with Vue
# Build a Node.js project that uses Vue.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - master

pool:
  vmImage: 'Ubuntu-16.04'

strategy:
  matrix:
    node_10_x:
      node_version: 10.x

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: $(node_version)
    displayName: 'Install Node.js'

  - script: |
      yarn
      yarn test:unit
      yarn build
    displayName: 'yarn install, test and build'
